# Generated by Django 5.0.6 on 2024-07-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Lote', 'Lote'), ('Tratamiento', 'Tratamiento'), ('Vacunación', 'Vacunación'), ('Tacto', 'Tacto'), ('Sangrado', 'Sangrado'), ('Estadísticas', 'Estadísticas')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sangrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('numeroCaravana', models.CharField(max_length=100)),
                ('numero_tubo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('numeroCaravana', models.IntegerField()),
                ('prenada', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCaravana', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('medicacion', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('cada', models.IntegerField()),
                ('durante', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_campo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('durante', models.IntegerField()),
                ('cada', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('numeroCaravana', models.CharField(max_length=100)),
                ('tipos', models.CharField(max_length=100)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('edad', models.FloatField(blank=True, null=True)),
                ('preniada', models.BooleanField(default=False)),
                ('reciennacida', models.BooleanField(default=False)),
                ('userId', models.IntegerField()),
                ('sangrado', models.ManyToManyField(to='miGanado.sangrado')),
                ('tratamientos', models.ManyToManyField(to='miGanado.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(default='Lote Nuevo', max_length=50)),
                ('numero', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('capacidad_max', models.IntegerField()),
                ('tipo_animal', models.CharField(choices=[('toro', 'Toro'), ('vaca', 'Vaca')], default='toro', max_length=20)),
                ('animales', models.ManyToManyField(blank=True, default=1, related_name='lotes_asociados', to='miGanado.animal')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='miGanado.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_notificaciones_lote', models.BooleanField(default=False)),
                ('recibir_notificaciones_tratamiento', models.BooleanField(default=False)),
                ('recibir_notificaciones_tacto', models.BooleanField(default=False)),
                ('recibir_notificaciones_sangrado', models.BooleanField(default=False)),
                ('recibir_notificaciones_estadisticas', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to='miGanado.usuario')),
            ],
        ),
    ]
