# Generated by Django 5.0.6 on 2024-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='numeroCaravana',
            field=models.CharField(max_length=100),
        ),
    ]
