# Generated by Django 5.0.6 on 2024-07-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangrado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miGanado.usuario'),
            preserve_default=False,
        ),
    ]
