# Generated by Django 5.0.6 on 2024-07-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0002_sangrado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sangrado',
            name='usuario',
        ),
    ]
