# Generated by Django 5.0.6 on 2024-07-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0002_animal_confignotificaciones_historialmedico_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='HistorialMedico',
        ),
        migrations.AddField(
            model_name='animal',
            name='fechaFallecimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='preniada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sangrado',
            field=models.ManyToManyField(to='miGanado.sangrado'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tratamientos',
            field=models.ManyToManyField(to='miGanado.tratamiento'),
        ),
        migrations.DeleteModel(
            name='HistorialMedico',
        ),
    ]
