# Generated by Django 5.0.6 on 2024-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0002_alter_tratamiento_numerocaravana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='numeroCaravana',
            field=models.CharField(max_length=100),
        ),
    ]
