# Generated by Django 5.0.6 on 2024-07-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0003_remove_animal_historialmedico_and_more'),
        ('miGanado', '0003_rename_numerocaravana_animal_numero_caravana_and_more'),
    ]

    operations = [
    ]
