# Generated by Django 5.0.6 on 2024-07-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0003_remove_sangrado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangrado',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
