# Generated by Django 5.0.6 on 2024-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0003_alter_animal_numerocaravana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='preniada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='reciennacida',
            field=models.BooleanField(default=False),
        ),
    ]
