# Generated by Django 5.0.6 on 2024-07-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0004_sangrado_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.IntegerField()),
                ('numero_animal', models.IntegerField()),
                ('prenada', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
