# Generated by Django 5.0.6 on 2024-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0004_alter_animal_preniada_alter_animal_reciennacida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='raza',
            new_name='tipos',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lote',
        ),
        migrations.AddField(
            model_name='animal',
            name='numero_lote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
