# Generated by Django 5.0.6 on 2024-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0005_rename_raza_animal_tipos_remove_animal_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='durante',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
