# Generated by Django 5.0.6 on 2024-07-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0006_tratamiento_durante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('durante', models.IntegerField()),
                ('cada', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
