# Generated by Django 5.0.6 on 2024-07-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0007_vacunacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
