# Generated by Django 5.0.6 on 2024-07-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0007_vacunacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sangrado',
            name='numero_animal',
        ),
        migrations.AddField(
            model_name='sangrado',
            name='numeroCaravana',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
