# Generated by Django 5.0.6 on 2024-07-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0008_remove_notificacion_usuario_notificacion_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('lote', 'Lote'), ('tratamiento', 'Tratamiento'), ('vacunacion', 'Vacunacion'), ('tacto', 'Tacto'), ('sangrado', 'Sangrado'), ('estadísticas', 'Estadísticas')], max_length=20),
        ),
    ]
