# Generated by Django 5.0.6 on 2024-07-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0008_remove_sangrado_numero_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nombre_lote',
            field=models.CharField(default='Lote Nuevo', max_length=50),
        ),
    ]
