# Generated by Django 5.0.6 on 2024-07-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0009_alter_notificacion_tipo'),
        ('miGanado', '0009_lote_nombre_lote'),
        ('miGanado', '0009_rename_numero_animal_tacto_numerocaravana'),
    ]

    operations = [
    ]
