# Generated by Django 5.0.6 on 2024-07-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miGanado', '0010_merge_20240715_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('Lote', 'Lote'), ('Tratamiento', 'Tratamiento'), ('Vacunación', 'Vacunación'), ('Tacto', 'Tacto'), ('Sangrado', 'Sangrado'), ('Estadísticas', 'Estadísticas')], max_length=20),
        ),
    ]
